# Form implementation generated from reading ui file '.\untitled.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(900, 600)
        self.all_market = QtWidgets.QWidget(parent=MainWindow)
        self.all_market.setObjectName("all_market")
        self.font_market = QtWidgets.QFrame(parent=self.all_market)
        self.font_market.setGeometry(QtCore.QRect(0, 0, 900, 700))
        self.font_market.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.font_market.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.font_market.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.font_market.setObjectName("font_market")
        self.market = QtWidgets.QFrame(parent=self.font_market)
        self.market.setGeometry(QtCore.QRect(20, 15, 371, 521))
        self.market.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.market.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.market.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.market.setObjectName("market")
        self.text = QtWidgets.QLabel(parent=self.market)
        self.text.setEnabled(True)
        self.text.setGeometry(QtCore.QRect(0, 50, 371, 91))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.text.setFont(font)
        self.text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.text.setWordWrap(False)
        self.text.setObjectName("text")
        self.placeBottle = QtWidgets.QFrame(parent=self.market)
        self.placeBottle.setGeometry(QtCore.QRect(30, 220, 181, 211))
        self.placeBottle.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.placeBottle.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.placeBottle.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.placeBottle.setObjectName("placeBottle")
        self.welcome_label = QtWidgets.QFrame(parent=self.market)
        self.welcome_label.setGeometry(QtCore.QRect(60, 150, 301, 41))
        self.welcome_label.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.welcome_label.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.welcome_label.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.welcome_label.setObjectName("welcome_label")
        self.welcome_text = QtWidgets.QLabel(parent=self.welcome_label)
        self.welcome_text.setGeometry(QtCore.QRect(-2, 10, 301, 20))
        self.welcome_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.welcome_text.setObjectName("welcome_text")
        self.info = QtWidgets.QFrame(parent=self.market)
        self.info.setGeometry(QtCore.QRect(240, 220, 120, 201))
        self.info.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.info.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.info.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.info.setObjectName("info")
        self.label_2 = QtWidgets.QLabel(parent=self.info)
        self.label_2.setGeometry(QtCore.QRect(3, 5, 116, 16))
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(parent=self.info)
        self.pushButton.setGeometry(QtCore.QRect(0, 168, 121, 31))
        self.pushButton.setStyleSheet("background-color: rgb(107, 95, 95);\n"
"  border-radius: 15%;\n"
"border : 1px solid black")
        self.pushButton.setObjectName("pushButton")
        self.menu_water = QtWidgets.QFrame(parent=self.info)
        self.menu_water.setGeometry(QtCore.QRect(5, 40, 30, 100))
        self.menu_water.setStyleSheet("")
        self.menu_water.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.menu_water.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.menu_water.setObjectName("menu_water")
        self.water1 = QtWidgets.QPushButton(parent=self.menu_water)
        self.water1.setGeometry(QtCore.QRect(3, 5, 24, 24))
        self.water1.setStyleSheet("\n"
"  border-radius: 12%;\n"
"  border: 1px solid red;")
        self.water1.setObjectName("water1")
        self.water5 = QtWidgets.QPushButton(parent=self.menu_water)
        self.water5.setGeometry(QtCore.QRect(3, 35, 24, 24))
        self.water5.setStyleSheet("\n"
"  border-radius: 12%;\n"
"  border: 1px solid red;")
        self.water5.setObjectName("water5")
        self.water19 = QtWidgets.QPushButton(parent=self.menu_water)
        self.water19.setGeometry(QtCore.QRect(3, 65, 24, 24))
        self.water19.setStyleSheet("\n"
"  border-radius: 12%;\n"
"  border: 1px solid red;")
        self.water19.setObjectName("water19")
        self.label_3 = QtWidgets.QLabel(parent=self.info)
        self.label_3.setGeometry(QtCore.QRect(45, 45, 66, 81))
        self.label_3.setStyleSheet("color: #000;\n"
"text-align: center;\n"
"font-size: 12px;\n"
"font-family: Alata;\n"
"font-style: normal;\n"
"font-weight: 400;\n"
"line-height: normal;")
        self.label_3.setObjectName("label_3")
        self.get_kard = QtWidgets.QFrame(parent=self.market)
        self.get_kard.setGeometry(QtCore.QRect(240, 435, 120, 80))
        self.get_kard.setStyleSheet("background-color: rgb(217, 217, 217);")
        self.get_kard.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.get_kard.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.get_kard.setObjectName("get_kard")
        self.kard_text = QtWidgets.QLabel(parent=self.get_kard)
        self.kard_text.setGeometry(QtCore.QRect(3, 25, 116, 16))
        self.kard_text.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.kard_text.setObjectName("kard_text")
        self.water = QtWidgets.QFrame(parent=self.market)
        self.water.setGeometry(QtCore.QRect(-1, 0, 376, 71))
        self.water.setStyleSheet("background-color: rgb(105, 255, 130);")
        self.water.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.water.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.water.setObjectName("water")
        MainWindow.setCentralWidget(self.all_market)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "1"))
        self.text.setText(_translate("MainWindow", "Дыхание родника \n"
" Water dispanser"))
        self.welcome_text.setText(_translate("MainWindow", "Приглашение"))
        self.label_2.setText(_translate("MainWindow", "Информация"))
        self.pushButton.setText(_translate("MainWindow", "пустк/стоп"))
        self.water1.setText(_translate("MainWindow", "1"))
        self.water5.setText(_translate("MainWindow", "5"))
        self.water19.setText(_translate("MainWindow", "19"))
        self.label_3.setText(_translate("MainWindow", "1л — 5р\n"
"\n"
"5л — 20р\n"
"\n"
"19л — 40р"))
        self.kard_text.setText(_translate("MainWindow", "Приложите карту"))
